<script setup lang="ts">
import { computed, ref } from 'vue'
import introJs from 'intro.js'
import 'intro.js/introjs.css'
import 'intro.js/themes/introjs-modern.css'

type ScenarioId = 'search-race' | 'mutual-exclusion' | 'bounded-concurrency' | 'single-flight' | 'cross-tab'
const props = defineProps<{ scenario: ScenarioId }>()
const toured = ref(false)
const lessons = {
  'search-race': { problem: 'A user types “ca” and then “cat”. The older request can finish last and replace the result for the newer intent.', naive: 'Commit every response as it arrives. This fails because completion order is not request order.', simple: 'Freshness protection lets only the response that still represents the user’s latest intent update the screen.', world: 'Product search: a keystroke starts a request; the search API responds; cancellation or a sequence token decides whether the response may commit.', flow: 'Request → response → commit decision → visible result', terms: [['Race condition', 'The result depends on unpredictable completion order.'], ['Stale response', 'A valid response for an intent that is no longer current.'], ['AbortSignal', 'A cancellation signal propagated to work that is no longer useful.'], ['Freshness token', 'A sequence value used to reject an older response at commit time.']], advantage: 'Prevents old data from replacing the user’s current intent.', cost: 'Cancellation must propagate; token guards still spend network and server work.', use: 'Autocomplete, route-driven fetching, or fast-changing read intent.', avoid: 'Independent requests whose results can safely coexist.', questions: ['Why can the first request finish last?', 'Where must freshness be checked?', 'What work does a token guard not save?'] },
  'mutual-exclusion': { problem: 'Two fast submits enter the same mutation before the first one finishes, producing duplicate effects.', naive: 'Disable a button and assume one JavaScript thread means no overlap. Await points still allow another task to enter.', simple: 'A mutex gives one local task at a time permission to cross a critical section.', world: 'Checkout: clicks become payment attempts; the mutex serializes local entry; a server idempotency key protects the remote charge.', flow: 'Intent → acquire → critical work → release → next waiter', terms: [['Critical section', 'Code that must not be owned by overlapping tasks.'], ['Mutex', 'A one-owner coordination primitive.'], ['FIFO', 'Waiters acquire in arrival order.'], ['Idempotency', 'Repeating an operation has no additional effect.']], advantage: 'Makes local ownership and ordering explicit.', cost: 'Adds waiting and cannot guarantee a remote exactly-once effect.', use: 'Overlapping local mutations of one protected resource.', avoid: 'Independent work or remote deduplication by itself.', questions: ['Why can async work overlap on one thread?', 'Why release in finally?', 'What does server idempotency add?'] },
  'bounded-concurrency': { problem: 'Starting every upload at once exhausts connections and makes failures compete with useful work.', naive: 'Use Promise.all over the entire batch. The batch has no admission control.', simple: 'A semaphore caps active work and queues the rest until capacity returns.', world: 'Photo upload: files are jobs; permits are upload slots; the queue holds files waiting for a connection.', flow: 'Job → queue → permit → active upload → release', terms: [['Semaphore', 'A counter that grants a limited number of permits.'], ['Capacity', 'The maximum active operations.'], ['Backpressure', 'Making excess work wait instead of overwhelming a dependency.'], ['Queue', 'Ordered work waiting for capacity.']], advantage: 'Protects dependencies and keeps load predictable.', cost: 'Lower limits increase waiting; higher limits increase pressure.', use: 'Uploads, API fan-out, workers, and resource pools.', avoid: 'Tiny batches or work already limited by the platform.', questions: ['What does capacity protect?', 'Why can more parallelism increase latency?', 'What happens after cancellation?'] },
  'single-flight': { problem: 'Several consumers request the same resource simultaneously and start duplicate producer work.', naive: 'Cache only completed values. Concurrent misses still launch separate requests.', simple: 'Single-flight shares one in-flight promise for a normalized key, then fans its outcome out to subscribers.', world: 'Profile loading: components are subscribers; the API call is the producer; the in-flight registry joins matching keys.', flow: 'Subscriber → normalized key → shared producer → fan-out', terms: [['Producer', 'The operation that creates the shared result.'], ['Subscriber', 'A caller waiting for that result.'], ['In-flight registry', 'The map of keys to currently running work.'], ['Fan-out', 'Delivering one outcome to several subscribers.']], advantage: 'Removes duplicate concurrent work for the same key.', cost: 'Keying and ownership are subtle; it is not a completed-value cache.', use: 'Concurrent identical reads or initialization.', avoid: 'Writes or requests with meaningfully different inputs.', questions: ['Why does a normal cache miss duplicate work?', 'Who owns producer cancellation?', 'When is the registry entry removed?'] },
  'cross-tab': { problem: 'Two browser tabs independently believe they should run the same background job.', naive: 'Keep an “already running” flag in memory. Each tab has separate memory.', simple: 'Cross-tab coordination elects one owner and makes every other tab a follower.', world: 'A messaging client: tabs are candidates; one owns synchronization; shared coordination broadcasts the decision.', flow: 'Tabs → claim → election → owner/followers → job result', terms: [['Owner', 'The tab allowed to run the shared job.'], ['Follower', 'A tab that observes instead of duplicating work.'], ['Election', 'The rule that deterministically selects one owner.'], ['Lease', 'Time-limited ownership used for crash recovery in production.']], advantage: 'Avoids duplicate browser work and conflicting effects.', cost: 'Production needs leases, heartbeats, and crash recovery.', use: 'Shared refresh, synchronization, or notification jobs across tabs.', avoid: 'Work that is cheap, isolated, or intentionally per-tab.', questions: ['Why does an in-memory flag fail?', 'How does a follower learn the owner?', 'Why does production need a lease?'] },
} as const
const lesson = computed(() => lessons[props.scenario])
const journey = computed(() => ({
  'search-race': {
    world: 'Picture an online store search. A shopper types “ca”, sees a spinner, then quickly adds “t”. Two couriers leave for the catalog service. The “cat” courier takes the fast route and returns first; the older “ca” courier is delayed, returns later, and hands the screen an obsolete parcel. If the screen accepts every parcel, the shopper sees broader, wrong results after expressing a more specific intent.',
    mapping: ['Shopper words → current intent', 'Courier trip → request', 'Catalog warehouse → API', 'Parcel arrival → response', 'Shelf update → state commit'],
    technical: 'Each issued request records a newer intent version. Cancellation asks obsolete work to stop, reducing waste when every adapter honors the signal. A freshness guard checks the version again at the commit boundary. The delayed “ca” response may still be valid data, but it cannot update the shelf because it no longer represents the shopper’s current words.',
    conclusion: 'We started with completion order controlling the UI. Latest-intent ownership solves it: cancel stale work when possible and always guard the final commit. Correctness improves, but the system now manages versions and cancellation lifecycles. Remember: a response can be valid and still be too old to own visible state.',
  },
  'mutual-exclusion': {
    world: 'Imagine a checkout where an impatient shopper presses Pay twice. Two attendants pick up the same order before either sees a receipt. If both reach the bank, the customer may be charged twice. A single cashier queue ensures only one attendant handles the order locally, while a receipt number lets the bank recognize that repeated messages describe the same purchase.',
    mapping: ['Shopper click → mutation intent', 'Cashier queue → mutex waiters', 'Cashier key → lock ownership', 'Bank charge → remote effect', 'Receipt number → idempotency key'],
    technical: 'Acquire grants one task ownership and queues the rest. The owner crosses the smallest possible critical section and releases in finally on success, failure, timeout, or cancellation. The next waiter then acquires. This serializes local entry; a server-enforced idempotency key separately prevents a retried or duplicated network message from creating another durable effect.',
    conclusion: 'We began with overlapping handlers creating duplicate effects. A mutex created one local owner, and idempotency protected the remote business intent. The trade-off is waiting and possible queue contention. Remember: the lock controls who may act now; the idempotency key controls whether the effect may happen again.',
  },
  'bounded-concurrency': {
    world: 'Picture a food-delivery kitchen receiving twenty orders at once but having only three preparation stations. Sending every order directly to a station creates crowding, mistakes, and slower meals. A dispatcher admits three orders, keeps the rest in a visible queue, and assigns the next order whenever a station becomes free. Cancelling a waiting order removes it without occupying a station.',
    mapping: ['Customer order → job', 'Dispatcher queue → waiting work', 'Preparation station → permit', 'Cooking → active operation', 'Finished meal → released capacity'],
    technical: 'A semaphore owns a fixed permit count. Every job must acquire before it becomes active and must release exactly once on every exit path. Excess work waits instead of competing for sockets, memory, or service quota. Capacity changes the balance: a larger number shortens the queue but raises dependency pressure; a smaller number protects the dependency but increases waiting.',
    conclusion: 'We started with an uncontrolled burst. Admission control made excess work wait and kept active load within a known bound. This improves stability at the cost of queue latency. Remember: a queue is not wasted time—it is the mechanism that keeps demand from becoming overload.',
  },
  'single-flight': {
    world: 'Imagine five desks in a hotel asking reception for the same guest record at the same moment. Without coordination, five staff members walk to the archive and copy the same folder. With a shared request board, the first staff member becomes the producer; the other desks subscribe to that trip and all receive the returned copy. A desk may stop waiting without automatically cancelling work needed by the others.',
    mapping: ['Desk → subscriber', 'Guest identifier → normalized key', 'Request board → in-flight registry', 'Archive trip → producer', 'Returned copies → fan-out'],
    technical: 'The first caller normalizes the resource key, creates the producer promise, and stores it before yielding. Later callers find that entry and await the same outcome. The entry is removed after success or failure so future calls can retry. This merges concurrent misses only; a separate cache decides whether an already completed value can be reused.',
    conclusion: 'We began with duplicate producers for one concurrent need. An in-flight registry gave the work one producer and many subscribers. The trade-off is careful key design and cancellation ownership. Remember: single-flight shares work that is happening now; caching reuses a value that already happened.',
  },
  'cross-tab': {
    world: 'Picture several browser tabs for one messaging account. Each tab notices that messages need synchronization and, because each has private memory, each believes no one else is working. A shared noticeboard lets every tab publish a claim. One deterministic election names an owner; followers observe instead of duplicating the job. A time-limited lease lets another tab recover if the owner disappears.',
    mapping: ['Browser window → contender', 'Shared noticeboard → browser coordination channel', 'Winning claim → owner', 'Observing tabs → followers', 'Expiry time → lease'],
    technical: 'Contenders publish ownership information through shared browser state. An election rule must produce the same winner for every observer. Only the owner runs the job; followers consume the result or wait for a change. Production designs add leases, heartbeats, and fencing tokens because tabs can sleep, crash, or resume with stale beliefs.',
    conclusion: 'We started with isolated tabs duplicating one shared job. Shared election created one owner and followers; leases make that ownership recoverable. Coordination adds failure-detection complexity and still cannot replace server authority. Remember: shared work needs shared ownership, not a flag trapped inside one tab.',
  },
})[props.scenario])
const depth = computed(() => ({
  'search-race': { junior: 'Imagine two shop assistants fetching products. The first starts “ca”, the second starts “cat”. Finishing first does not mean starting first. The screen needs a rule that follows the shopper’s newest words.', mechanism: 'Issuing a request records intent. Abort protection tries to stop superseded work; a freshness guard compares a monotonically increasing sequence immediately before commit. The commit boundary—not response arrival—is where visible correctness is decided.', mistakes: 'Common mistakes: debouncing without a commit guard, treating abort as guaranteed, reusing a controller after cancellation, or checking freshness before an await but not after it.', advanced: 'Cancellation can reduce client parsing and server work only when every layer propagates it. A token guard is the reliable correctness boundary; cancellation is an optimization. Streaming responses and multi-source aggregation need a freshness rule per commit unit.' },
  'mutual-exclusion': { junior: 'Picture a shopper clicking “Pay” twice. Both click handlers reach an await, so the second can enter before the first returns. One cashier queue prevents two local owners; the receipt number prevents the bank from charging twice.', mechanism: 'Acquire either grants ownership or appends a waiter to a FIFO queue. The owner runs the critical section and releases in finally. The next non-cancelled waiter receives ownership. An idempotency key independently identifies the remote business intent.', mistakes: 'Common mistakes: using only a disabled button, forgetting finally, holding the lock across unrelated work, allowing cancelled waiters to remain queued, or calling a mutex an exactly-once guarantee.', advanced: 'A mutex increases tail latency and can create convoys. Scope locks by resource, keep critical sections small, and use server-enforced uniqueness or idempotency for effects that survive the browser.' },
  'bounded-concurrency': { junior: 'Uploading eight photos at once is like sending eight trucks through a two-bay loading dock. A waiting line feels slower for one file, but prevents every file from blocking the dock.', mechanism: 'Each job acquires one permit before becoming active. Capacity is decremented on acquire and restored exactly once on release. FIFO waiters receive returned permits; cancellation removes a waiter without consuming capacity.', mistakes: 'Common mistakes: using Promise.all as admission control, releasing twice, forgetting rejected jobs, setting capacity from guesswork, or keeping cancelled work in the queue.', advanced: 'Tune capacity against dependency saturation, browser connection limits, memory, and service quotas. Adaptive limits can respond to latency and errors, but are harder to reason about than a conservative fixed bound.' },
  'single-flight': { junior: 'Three profile widgets open together. Without coordination, each phones the same API. Single-flight is one caller placing the call while the others listen to the same answer.', mechanism: 'Normalize the resource key, check the in-flight registry, store the new producer promise before yielding, and return that promise to later callers. Remove the entry after success or failure so a future request can retry.', mistakes: 'Common mistakes: confusing in-flight deduplication with caching, using incomplete keys, letting one subscriber cancel shared work, or retaining rejected promises forever.', advanced: 'Producer ownership needs an explicit policy. Shared authentication context, response variants, and tenant boundaries must be part of the key. Stale-while-refresh is a separate cache layer composed around single-flight.' },
  'cross-tab': { junior: 'Two messaging tabs both notice that notifications need refreshing. A note kept inside one tab cannot warn the other. They need a shared noticeboard and a rule for who owns the work.', mechanism: 'Each contender publishes a claim to a shared browser channel. A deterministic election selects one tab; followers observe the owner and suppress duplicate work. Production ownership expires through a lease so another tab can recover after a crash.', mistakes: 'Common mistakes: relying on module memory, assuming a storage write is a transaction, never expiring ownership, or failing to handle suspended and crashed tabs.', advanced: 'Use BroadcastChannel or storage events for notification, but pair ownership with timestamps, heartbeats, fencing tokens, and conflict resolution. Browser coordination cannot replace server authority for globally unique effects.' },
})[props.scenario])
const tourLesson = computed(() => ({
  'search-race': ['Choose “older ca arrives last” and predict which query an unprotected UI will show.', 'Switch between cancellation and a freshness token. Both preserve “cat”, but only cancellation attempts to stop wasted work.', 'Run the race. Follow the highlighted request path from keystroke to commit decision.', 'Compare the lanes and explain why response validity is different from response freshness.'],
  'mutual-exclusion': ['Choose a payment and predict what two overlapping clicks can do.', 'Change the first ending to failure or cancellation. Watch for release on every exit path.', 'Run, then reveal events. Follow acquire → ownership → effect → finally release.', 'Compare duplicate effects with serialized ownership, then state why server idempotency is still required.'],
  'bounded-concurrency': ['Choose more files than permits and predict the queue depth.', 'Change capacity. Notice the trade-off: fewer permits protect the service but increase waiting.', 'Run the batch and follow one file from queue to permit to active upload to release.', 'Compare peak active work. Explain why waiting can improve total system reliability.'],
  'single-flight': ['Choose several subscribers requesting the same profile and predict producer calls.', 'Toggle subscriber cancellation. Notice that listener ownership differs from producer ownership.', 'Run the reads and follow normalized key → registry → shared producer → fan-out.', 'Compare producer counts, then explain why this is not a completed-value cache.'],
  'cross-tab': ['Imagine two messaging tabs both starting one sync job. Predict the duplicate effect.', 'Inspect this tab ID: it is a contender, not automatically the owner.', 'Coordinate the tab and follow claim → election → owner or follower.', 'Compare independent claims with shared ownership, then explain why production also needs leases.'],
})[props.scenario])
const labels = computed(() => ({ problem: 'First, feel the problem', naive: 'Why the naive approach fails', simple: 'The concept, in plain language', world: 'Production mapping', terms: 'Terms you can inspect', trade: 'Trade-offs and decisions', advantage: 'Advantage', cost: 'Cost', use: 'Use it when', avoid: 'Avoid it when', check: 'Can you explain it?', start: toured.value ? 'Restart guided lesson' : 'Start guided lesson' }))
function startTour() { toured.value = true; const tour = introJs.tour().setOptions({ showProgress: true, showBullets: false, nextLabel: 'Next', prevLabel: 'Back', doneLabel: 'Done', skipLabel: 'Skip', steps: [
  { element: '.problem-block', intro: `Make a prediction. ${tourLesson.value[0]}` },
  { element: '.comparison-controls', intro: tourLesson.value[1] },
  { element: '.comparison-controls .primary-action', intro: `${tourLesson.value[2]} This highlighted control runs the real comparison; use it after the tour and inspect the result.` },
  { element: '.scenario-stepper', intro: 'This is live simulator state, not a click counter. Completed, current, warning, and upcoming steps follow the actual run.' },
  { element: '.why-panel', intro: 'Read the live tutor: it records your transition, the internal reaction, the result, and the concept—even when the result stays the same.' },
  { element: '.comparison-results', intro: tourLesson.value[3] },
] }); void tour.start() }
</script>
<template>
  <VContainer class="learning-frame page-rail">
    <section class="problem-block"><p class="kicker">01</p><h2>{{ labels.problem }}</h2><p>{{ lesson.problem }}</p><aside><strong>{{ labels.naive }}</strong><p>{{ lesson.naive }}</p></aside></section>
    <div class="learning-grid"><section><p class="kicker">02</p><h2>{{ labels.world }}</h2><p>{{ journey.world }}</p><ul class="concept-mapping"><li v-for="item in journey.mapping" :key="item">{{ item }}</li></ul></section><section><p class="kicker">03</p><h2>{{ labels.simple }}</h2><p>{{ lesson.simple }}</p><p>{{ journey.technical }}</p><code class="system-flow">{{ lesson.flow }}</code></section></div>
    <details class="terminology"><summary>{{ labels.terms }}</summary><dl><div v-for="term in lesson.terms" :key="term[0]"><dt>{{ term[0] }}</dt><dd>{{ term[1] }}</dd></div></dl></details>
    <div class="depth-layers"><details open><summary>Beginner · follow the story</summary><p>{{ depth.junior }}</p></details><details><summary>Intermediate · internal mechanism</summary><p>{{ depth.mechanism }}</p></details><details><summary>Common mistakes</summary><p>{{ depth.mistakes }}</p></details><details><summary>Advanced · limits and architecture</summary><p>{{ depth.advanced }}</p></details></div>
    <button class="primary-action tour-trigger" type="button" @click="startTour">{{ labels.start }}</button>
  </VContainer>
  <slot />
  <VContainer class="learning-frame learning-summary page-rail"><section class="mental-model"><p class="kicker">04</p><h2>Conclusion and mental model</h2><p>{{ journey.conclusion }}</p></section><section><h2>{{ labels.trade }}</h2><dl class="decision-grid"><div><dt>{{ labels.advantage }}</dt><dd>{{ lesson.advantage }}</dd></div><div><dt>{{ labels.cost }}</dt><dd>{{ lesson.cost }}</dd></div><div><dt>{{ labels.use }}</dt><dd>{{ lesson.use }}</dd></div><div><dt>{{ labels.avoid }}</dt><dd>{{ lesson.avoid }}</dd></div></dl></section><section><p class="kicker">05</p><h2>{{ labels.check }}</h2><ol><li v-for="question in lesson.questions" :key="question">{{ question }}</li></ol></section></VContainer>
</template>
