<script setup lang="ts">
import { computed, ref } from 'vue'; import { useI18n } from 'vue-i18n'; import { runUploadComparison, type UploadRun } from '@concurrency-lab/scenario-engine'
const { locale } = useI18n(); const jobs = ref(6); const capacity = ref(2); const cancelQueued = ref(true); const comparison = ref<ReturnType<typeof runUploadComparison> | null>(null); const step = ref(0)
const total = computed(() => comparison.value ? Math.max(comparison.value.broken.events.length, comparison.value.fixed.events.length) : 0); const fa = computed(() => locale.value === 'fa')
function run() { comparison.value = runUploadComparison({ seed: 'phase-4', jobs: jobs.value, capacity: capacity.value, ...(cancelQueued.value ? { cancelJob: jobs.value } : {}) }); step.value = 1 }
function events(lane: UploadRun) { return lane.events.slice(0, step.value) }
function latestMetric(lane: UploadRun, name: 'active' | 'available') { for (const event of [...events(lane)].reverse()) { const value = (event.detail as Record<string, unknown>)[name]; if (typeof value === 'number') return value } return name === 'available' ? lane.capacity : 0 }
function maxWait(lane: UploadRun) { return Math.max(0, ...lane.waitTimes) }
</script>
<template><section class="comparison-controls"><h2>{{ fa ? 'آزمایش صف بارگذاری' : 'Upload queue experiment' }}</h2><p>{{ fa ? 'دو مسیر دقیقاً همان فایل‌ها و ظرفیت اعلام‌شده را می‌گیرند. مسیر خراب ظرفیت را نادیده می‌گیرد؛ مسیر اصلاح‌شده permit می‌گیرد.' : 'Both lanes receive the same files and declared capacity. The broken lane ignores it; the fixed lane must acquire a permit.' }}</p><div class="controls comparison-control-grid"><label>{{ fa ? 'تعداد فایل' : 'Jobs' }}<input v-model.number="jobs" type="number" min="3" max="8" /></label><label>{{ fa ? 'ظرفیت' : 'Capacity' }}<input v-model.number="capacity" type="number" min="1" max="4" /></label><label><input v-model="cancelQueued" type="checkbox" /> {{ fa ? 'لغو آخرین کار در صف' : 'Cancel last queued job' }}</label></div><div class="action-row"><button class="primary-action" @click="run">{{ fa ? 'اجرای مقایسه' : 'Run comparison' }}</button><button v-if="comparison && step < total" class="secondary-action" @click="step++">{{ fa ? 'رویداد بعدی' : 'Reveal next event' }}</button></div></section><section v-if="comparison" class="comparison-results"><div class="comparison-grid"><article v-for="lane in ([comparison.broken, comparison.fixed] as UploadRun[])" :key="lane.variant" class="result-panel" :class="lane.variant === 'broken' ? 'lane-broken' : 'lane-fixed'"><h3>{{ lane.variant === 'broken' ? (fa ? 'بدون محدودیت' : 'Unbounded') : (fa ? 'semaphore' : 'Semaphore protected') }}</h3><dl class="metric-grid"><div><dt>{{ fa ? 'فعال اکنون' : 'Active now' }}</dt><dd>{{ latestMetric(lane, 'active') }}</dd></div><div><dt>{{ fa ? 'permit آزاد' : 'Available permits' }}</dt><dd>{{ latestMetric(lane, 'available') }}</dd></div><div><dt>{{ fa ? 'عمق بیشینهٔ صف' : 'Max queue' }}</dt><dd>{{ lane.maxQueueDepth }}</dd></div><div><dt>{{ fa ? 'بیشترین انتظار' : 'Max wait' }}</dt><dd>{{ maxWait(lane) }}ms</dd></div><div><dt>{{ fa ? 'بیشینهٔ فعال' : 'Peak active' }}</dt><dd>{{ lane.peakActive }}</dd></div><div><dt>{{ fa ? 'لغوشده' : 'Cancelled' }}</dt><dd>{{ lane.cancelled }}</dd></div></dl><p :class="lane.invariant.passed ? 'pass-label' : 'failure-badge'">{{ lane.invariant.passed ? (fa ? 'ظرفیت رعایت شد' : 'Capacity respected') : (fa ? 'ظرفیت نقض شد' : 'Capacity exceeded') }}</p><ol class="timeline" aria-live="polite"><li v-for="event in events(lane)" :key="event.sequence"><span class="sequence">{{ event.sequence }}</span><span class="event-time">{{ event.timestamp }}ms</span><strong>{{ event.label }}</strong><span class="event-kind">{{ event.kind }}</span></li></ol></article></div></section></template>
