<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { runSingleFlightComparison, type SingleFlightRun } from '@concurrency-lab/scenario-engine'
import { timelineLabel } from '../../components/timeline-label'
import WhyPanel from '../../components/WhyPanel.vue'
import WorkspaceNavigator from '../../components/WorkspaceNavigator.vue'
import ScenarioStateStepper from '../../components/ScenarioStateStepper.vue'
const id = ref('Moein'); const subscribers = ref(3); const cancelOne = ref(true); const swr = ref(true); const comparison = ref<ReturnType<typeof runSingleFlightComparison> | null>(null); const step = ref(0); const total = computed(() => comparison.value ? Math.max(comparison.value.broken.events.length, comparison.value.fixed.events.length) : 0)
const feedback = ref({ change: 'Nothing yet — configure the profile readers.', system: 'Three components are ready to request the same profile.', why: 'A completed-value cache cannot merge misses that happen at the same time.', result: 'Run the comparison to count producer calls and delivered outcomes.', concept: 'Single-flight', unchanged: true, activeStep: 0 })
const tutorFlow = ['Subscribers', 'Normalized key', 'In-flight registry', 'Shared producer', 'Fan-out']
const invalid = computed(() => id.value.trim().length === 0 || subscribers.value < 2 || subscribers.value > 5)
const interactionStep = computed(() => !comparison.value ? (id.value.trim() ? 0 : 1) : step.value < total.value ? Math.min(3, Math.max(1, Math.ceil((step.value / total.value) * 4))) : 4)
const interactionReason = computed(() => invalid.value ? 'Resource ID is required and subscribers must be between 2 and 5.' : !comparison.value ? 'Subscribers are ready to request the same normalized key.' : step.value < total.value ? 'The registry owns the producer while the outcome fans out.' : 'The shared producer completed and delivered to active subscribers.')
watch(id, (next, previous) => { feedback.value = { change: `Resource ID: “${previous}” → “${next}”`, system: `The registry key will normalize to profile:${next.trim().toLowerCase()}.`, why: 'Trim and lowercase make semantically identical IDs join the same in-flight entry.', result: 'No request has run yet, so producer counts stay unchanged until execution.', concept: 'Key normalization', unchanged: true, activeStep: 1 } })
watch(subscribers, (next, previous) => { feedback.value = { change: `Subscribers: ${previous} → ${next}`, system: `${next} callers now look up the same normalized in-flight key.`, why: 'The fixed registry returns the existing promise after the first caller creates it.', result: `The broken lane will make ${next} producer calls; the fixed lane still makes one.`, concept: 'Promise coalescing', unchanged: false, activeStep: 2 } })
watch(cancelOne, (next) => { feedback.value = next ? { change: 'Subscriber cancellation: off → on', system: 'Subscriber 2 stops listening while the shared producer keeps running.', why: 'One consumer does not own work shared with other consumers.', result: 'Delivered count falls by one, but producer calls stay at one.', concept: 'Subscriber vs producer ownership', unchanged: true, activeStep: 3 } : { change: 'Subscriber cancellation: on → off', system: 'Every subscriber remains attached to the shared outcome.', why: 'No listener detaches before fan-out.', result: 'All subscribers receive the result; producer count remains one.', concept: 'Outcome fan-out', unchanged: false, activeStep: 4 } })
watch(swr, (next) => { feedback.value = { change: `Cached placeholder during refresh: ${!next} → ${next}`, system: next ? 'A stale value is shown while the producer refreshes.' : 'Consumers wait without a stale placeholder.', why: 'Stale-while-refresh is cache composition outside the single-flight registry.', result: 'Producer deduplication does not change; only the waiting experience changes.', concept: 'Single-flight is not caching', unchanged: true, activeStep: 3 } })
function run() { if (invalid.value) { comparison.value = null; step.value = 0; feedback.value = { change: 'The read configuration was rejected.', system: 'No registry entry or producer was created.', why: 'A blank key or unsupported subscriber count cannot identify this deterministic fixture.', result: 'Correct the fields before running.', concept: 'Key validation', unchanged: true, activeStep: 1 }; return } comparison.value = runSingleFlightComparison({ seed: 'phase-5', resourceId: id.value, subscribers: subscribers.value, ...(cancelOne.value ? { cancelSubscriber: 2 } : {}), staleWhileRefresh: swr.value }); step.value = 1; feedback.value = { change: `Ran ${subscribers.value} concurrent reads for “${id.value}”.`, system: `The key ${comparison.value.key} points all fixed callers to one in-flight producer.`, why: 'The registry stores the promise before another caller can create duplicate work.', result: `${comparison.value.broken.producerCalls} producer calls without protection versus ${comparison.value.fixed.producerCalls} with single-flight.`, concept: 'In-flight deduplication', unchanged: false, activeStep: 3 } }
function revealNext() { if (!comparison.value || step.value >= total.value) return; step.value += 1; const event = comparison.value.fixed.events[step.value - 1]; feedback.value = { change: `Revealed event ${step.value} of ${total.value}.`, system: event ? `The shared registry recorded “${event.label}”.` : 'The fan-out trace advanced.', why: 'The trace separates subscriber activity from ownership of the shared producer.', result: step.value >= total.value ? `One producer delivered to ${comparison.value.fixed.delivered} active subscribers.` : 'The next registry or delivery transition is ready to inspect.', concept: event?.kind === 'commit' ? 'Outcome fan-out' : 'Progressive single-flight evidence', unchanged: false, activeStep: interactionStep.value } }
function reset() { id.value = 'Moein'; subscribers.value = 3; cancelOne.value = true; swr.value = true; comparison.value = null; step.value = 0; feedback.value = { change: 'Reset the profile readers.', system: 'Three subscribers are waiting outside an empty in-flight registry.', why: 'Reset removes the previous producer and delivery trace.', result: 'No producer exists until you run again.', concept: 'Clean initial state', unchanged: true, activeStep: 0 } }
function events(lane: SingleFlightRun) { return lane.events.slice(0, step.value) }
</script>
<template>
  <section class="simulator-workspace" data-scenario="single-flight">
  <WorkspaceNavigator />
  <ScenarioStateStepper :steps="tutorFlow" :current="interactionStep" :tone="invalid ? 'error' : 'neutral'" :reason="interactionReason" />
  <VCard tag="section" class="comparison-controls" variant="outlined"><VCardText><h2>Fan-out experiment</h2><p class="panel-copy">The key is normalized with trim and lowercase. Both lanes have the same subscribers; only the fixed registry coalesces concurrent work.</p><div class="controls comparison-control-grid"><label>Resource ID<input v-model="id" /></label><label>Subscribers<input v-model.number="subscribers" type="number" min="2" max="5" /></label><label><input v-model="cancelOne" type="checkbox"/> Cancel subscriber 2</label><label><input v-model="swr" type="checkbox"/> Show cached value during refresh</label></div><div class="action-row"><button class="primary-action" type="button" :disabled="invalid" @click="run">Run comparison</button><button v-if="comparison&&step<total" class="secondary-action" type="button" @click="revealNext">Reveal next event</button><button class="secondary-action" type="button" @click="reset">Reset</button></div></VCardText></VCard>
  <div class="workspace-outcome"><WhyPanel v-bind="feedback" :flow="tutorFlow" /><section class="comparison-results"><VCard v-if="!comparison" class="comparison-empty" variant="tonal"><VCardText>Run the reads to reveal registry ownership and fan-out.</VCardText></VCard><template v-else><p><strong>Normalized key:</strong> <code>{{comparison.key}}</code></p><VRow class="comparison-grid ma-0"><VCol v-for="lane in ([comparison.broken,comparison.fixed] as SingleFlightRun[])" :key="lane.variant" class="pa-0" cols="12"><VCard tag="article" class="result-panel h-100" :class="lane.variant==='broken'?'lane-broken':'lane-fixed'" variant="outlined"><VCardText><h3>{{lane.variant==='broken'?'Independent requests':'Single-flight'}}</h3><dl class="metric-grid"><div><dt>Producer calls</dt><dd>{{lane.producerCalls}}</dd></div><div><dt>Delivered</dt><dd>{{lane.delivered}}</dd></div></dl><VChip :class="lane.invariant.passed?'pass-label':'failure-badge'" :color="lane.invariant.passed ? 'success' : 'error'" variant="tonal">{{lane.invariant.passed?'One shared producer':'Duplicate producers'}}</VChip><ol class="timeline" tabindex="0" aria-label="Event timeline" aria-live="polite"><li v-for="event in events(lane)" :key="event.sequence" tabindex="-1"><span class="sequence">{{event.sequence}}</span><span class="event-time">{{event.timestamp}}ms</span><strong>{{timelineLabel(event.kind,event.label)}}</strong><span class="event-kind">{{event.kind}}</span></li></ol></VCardText></VCard></VCol></VRow></template></section></div>
  </section>
</template>
