<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { runMutualExclusionComparison, type MutationExample, type MutationOutcome, type MutualExclusionRun } from '@concurrency-lab/scenario-engine'
const { locale } = useI18n()
const example = ref<MutationExample>('payment'); const outcome = ref<MutationOutcome>('success')
const comparison = ref<ReturnType<typeof runMutualExclusionComparison> | null>(null); const step = ref(0)
const text = computed(() => locale.value === 'fa' ? { controls: 'آزمایش قطعی', example: 'نمونه', payment: 'پرداخت دوباره', save: 'ذخیرهٔ فرم', ending: 'پایان تلاش نخست', success: 'موفقیت', failure: 'خطا', timeout: 'پایان مهلت', cancellation: 'لغو', run: 'اجرای مقایسه', next: 'رویداد بعدی', replay: 'بازپخش', broken: 'بدون محافظ', fixed: 'mutex صفی + کلید idempotency', pending: 'قانون هنوز ارزیابی نشده', held: 'قانون حفظ شد', violated: 'قانون نقض شد', effects: 'اثرها', peak: 'بیشترین بخش بحرانی فعال', evidence: 'ردیابی مرحله‌ای', explain: 'مسیر اصلاح‌شده برای مالکیت از mutex و برای جلوگیری از اثر دوم از سیاست جداگانهٔ idempotency استفاده می‌کند.', limit: 'لغو و timeout مشارکتی‌اند: mutex فقط آزادشدن محلی را تضمین می‌کند و اثر راه‌دور انجام‌شده را برنمی‌گرداند.' } : { controls: 'Deterministic experiment', example: 'Example', payment: 'Payment double-submit', save: 'Save-form overlap', ending: 'First attempt ending', success: 'Success', failure: 'Failure', timeout: 'Timeout', cancellation: 'Cancellation', run: 'Run comparison', next: 'Reveal next event', replay: 'Replay trace', broken: 'No protection', fixed: 'FIFO mutex + idempotency key', pending: 'Invariant not evaluated yet', held: 'Invariant held', violated: 'Invariant violated', effects: 'Effects', peak: 'Peak active critical sections', evidence: 'Progressive evidence', explain: 'The fixed lane uses a mutex for ownership and a separate idempotency policy to prevent a second effect.', limit: 'Cancellation and timeout are cooperative: a mutex guarantees local release, but cannot undo a remote effect that already happened.' })
const total = computed(() => comparison.value ? Math.max(comparison.value.broken.events.length, comparison.value.fixed.events.length) : 0)
function run() { comparison.value = runMutualExclusionComparison({ seed: 'phase-3', example: example.value, outcome: outcome.value }); step.value = 1 }
function events(lane: MutualExclusionRun) { return lane.events.slice(0, step.value) }
function done(lane: MutualExclusionRun) { return events(lane).some((event) => event.kind === 'invariant') }
</script>
<template><section class="comparison-controls" aria-labelledby="mutex-controls"><div class="panel-heading"><div><p class="kicker">{{ text.controls }}</p><h2 id="mutex-controls">{{ locale === 'fa' ? 'یک ورودی، دو سیاست مالکیت' : 'One input, two ownership policies' }}</h2></div></div><p>{{ text.explain }}</p><div class="controls comparison-control-grid"><label>{{ text.example }}<select v-model="example" :disabled="!!comparison && step < total"><option value="payment">{{ text.payment }}</option><option value="save">{{ text.save }}</option></select></label><label>{{ text.ending }}<select v-model="outcome" :disabled="!!comparison && step < total"><option value="success">{{ text.success }}</option><option value="failure">{{ text.failure }}</option><option value="timeout">{{ text.timeout }}</option><option value="cancellation">{{ text.cancellation }}</option></select></label></div><div class="action-row"><button class="primary-action" type="button" @click="run">{{ comparison ? text.replay : text.run }} ▶</button><button v-if="comparison && step < total" class="secondary-action" type="button" @click="step++">{{ text.next }} →</button><span v-if="comparison">{{ step }} / {{ total }}</span></div></section><section v-if="comparison" class="comparison-results" aria-labelledby="mutex-results"><h2 id="mutex-results">{{ text.evidence }}</h2><div class="comparison-grid"><article v-for="lane in ([comparison.broken, comparison.fixed] as MutualExclusionRun[])" :key="lane.variant" class="result-panel" :class="lane.variant === 'broken' ? 'lane-broken' : 'lane-fixed'"><div class="panel-heading"><h3>{{ lane.variant === 'broken' ? text.broken : text.fixed }}</h3><span :class="done(lane) && lane.invariant.passed ? 'pass-label' : done(lane) ? 'failure-badge' : 'count-badge'">{{ !done(lane) ? text.pending : lane.invariant.passed ? text.held : text.violated }}</span></div><dl class="metric-grid"><div><dt>{{ text.effects }}</dt><dd>{{ done(lane) ? lane.effects : '—' }}</dd></div><div><dt>{{ text.peak }}</dt><dd>{{ done(lane) ? lane.peakCriticalSections : '—' }}</dd></div></dl><ol class="timeline" aria-live="polite"><li v-for="event in events(lane)" :key="event.sequence" :class="`event-${event.kind}`"><span class="sequence">{{ String(event.sequence).padStart(2, '0') }}</span><span class="event-time">{{ event.timestamp }}ms</span><strong>{{ event.label }}</strong><span class="event-kind">{{ event.kind }}</span></li></ol></article></div><aside class="prediction-card"><strong>{{ locale === 'fa' ? 'محدودیت مهم' : 'Important limitation' }}</strong><p>{{ text.limit }}</p></aside></section></template>
