export { runBrokenSearchRace, type BrokenSearchOptions } from './application/run-broken-search-race'
export { runFixedSearchRace, type FixedSearchOptions } from './application/run-fixed-search-race'
export { runSearchRaceComparison, type SearchRaceComparisonOptions } from './application/run-search-race-comparison'
export { SeededLatencyGenerator } from './domain/seeded-latency'
export type { SearchProtectionStrategy, SearchRaceComparison, SearchRaceRun, SearchRequest, SearchResult } from './domain/scenario'
export { runMutualExclusionComparison, type MutualExclusionOptions } from './application/run-mutual-exclusion-comparison'
export type { MutationExample, MutationOutcome, MutualExclusionComparison, MutualExclusionRun } from './domain/mutual-exclusion'
export { runUploadComparison, type UploadOptions } from './application/run-upload-comparison'
export type { UploadComparison, UploadRun } from './domain/bounded-concurrency'
